name: dostuff

on: workflow_dispatch

jobs:
  do-stuff:
    runs-on: windows-latest
    steps:
      - name: get sha from PR number and save output
        id: get-sha
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('here');
